In [3]:
import numpy as np

In [4]:
np.__version__

'1.14.3'

# numpy.array

In [5]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
nparr[5]

5

In [10]:
nparr[5] = 23
nparr

array([ 0,  1,  2,  3,  4, 23,  6,  7,  8,  9])

In [11]:
nparr[5] = 'str'
nparr

ValueError: invalid literal for int() with base 10: 'str'

In [13]:
nparr.dtype

dtype('int32')

In [14]:
nparr[3] = 3.14
nparr

array([ 0,  1,  2,  3,  4, 23,  6,  7,  8,  9])

In [15]:
nparr.dtype

dtype('int32')

# numpy.array 创建数组和矩阵

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10).dtype

dtype('float64')

In [18]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.zeros(5,5)

TypeError: data type not understood

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros(shape=(5,5), dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.zeros(shape=(4,4), dtype='int', fill_value=32)

TypeError: 'fill_value' is an invalid keyword argument for this function

In [26]:
np.full(shape=(4,4), dtype='int', fill_value=32)

array([[32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32]])

In [27]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [28]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [29]:
np.random.randint(0,10)

2

In [30]:
np.random.randint(0,10,10)

array([9, 8, 6, 9, 7, 6, 6, 1, 1, 3])

In [31]:
np.random.randint(0,10, size=(2,2))

array([[0, 2],
       [9, 0]])

In [32]:
np.random.seed(22)
np.random.randint(0,10, size=(2,2))

array([[5, 4],
       [0, 4]])

In [33]:
np.random.randint(0,10, size=(2,2))

array([[6, 6],
       [4, 8]])

In [34]:
np.random.random(0,10, size=(2,2))

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [35]:
np.random.random()    # 0 ~ 1 

0.3388639606037004

In [36]:
np.random.random((3,3))

array([[0.27053283, 0.69104135, 0.22040452],
       [0.81195092, 0.01052687, 0.5612037 ],
       [0.81372619, 0.7451003 , 0.18911136]])

In [40]:
np.random.normal()

1.5567437555275854

In [42]:
np.random.normal(0, 1, (3,5))

array([[ 1.67564666,  0.69701334,  0.16128293, -0.1386186 ,  0.05575381],
       [ 1.68796308, -0.04594775, -1.08663009, -1.9637195 ,  0.16411715],
       [-0.07990946, -0.58257901,  0.85780442,  0.45404093, -1.4069008 ]])

In [43]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [44]:
np.random.random?