#  https://docs.scipy.org

# py list  --> np  array

In [1]:
list_a = [1,2,3,4]
list_b = [2,3,5,6]

In [2]:
import numpy as np

# 1. list ---> array

In [4]:
array_a = np.array(list_a)
array_a

array([1, 2, 3, 4])

In [5]:
array_b = np.array(list_b)
array_b

array([2, 3, 5, 6])

    # 二维数组

In [6]:
array_ab = np.array([array_a,array_b])
array_ab

array([[1, 2, 3, 4],
       [2, 3, 5, 6]])

# 2 arange

In [11]:
array_c = np.arange(1,10,2)
array_c

array([1, 3, 5, 7, 9])

# 3 zeros ones eye

In [13]:
array_d = np.zeros((2,4))
array_d
# 默认为 float

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
array_d.dtype

dtype('float64')

In [20]:
array_e = np.eye(4, dtype=int)  # eye 就是 方阵， 无需传 row , col 两个参数
array_e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#  二维数组的切片

In [24]:
array_44 = np.arange(16).reshape(4,4)
array_44

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
array_22 = array_44[1:3,1:3]
array_22

array([[ 5,  6],
       [ 9, 10]])

# random

In [35]:
#"continuous uniform" distribution [0,1)
array_rnd = np.random.random(4)
array_rnd

array([0.83479771, 0.72104873, 0.65406236, 0.65417188])

In [30]:
np.random.random?

In [32]:
np.random.randn?

# "standard normal" distribution

In [31]:
array_gau = np.random.randn(8)
array_gau

array([ 0.05671987, -1.93323435, -0.06281844, -0.61815478,  0.28703403,
        0.09600241, -1.53507467,  0.32314068])

In [39]:
array_int = np.random.randint(low=1,high=10,size=10)
array_int

array([2, 3, 3, 6, 6, 6, 3, 6, 5, 2])

In [37]:
np.random.randint?

# matrix

In [ ]:
# 用二维数组来 dot 还是不方便

In [40]:
mat_a = np.mat(np.random.randint(10,size=20).reshape(4,5))
mat_b = np.mat(np.random.randint(10,size=20).reshape(5,4))

In [41]:
mat_a

matrix([[0, 4, 5, 3, 4],
        [6, 6, 0, 7, 0],
        [0, 9, 5, 7, 2],
        [0, 0, 5, 5, 0]])

In [42]:
mat_b

matrix([[5, 6, 7, 7],
        [4, 1, 6, 9],
        [7, 4, 9, 3],
        [4, 7, 4, 5],
        [6, 7, 9, 1]])

In [43]:
mat_a * mat_b

matrix([[ 87,  73, 117,  70],
        [ 82,  91, 106, 131],
        [111,  92, 145, 133],
        [ 55,  55,  65,  40]])

In [44]:
mat_a.T

matrix([[0, 6, 0, 0],
        [4, 6, 9, 0],
        [5, 0, 5, 5],
        [3, 7, 7, 5],
        [4, 0, 2, 0]])

In [48]:
mat_a.I

matrix([[ 0.1282365 ,  0.14137985, -0.16103568, -0.00831228],
        [-0.03844332, -0.01468266,  0.13230186, -0.11772971],
        [ 0.07696558, -0.03425955, -0.02462899,  0.091964  ],
        [-0.07696558,  0.03425955,  0.02462899,  0.108036  ],
        [ 0.24996053,  0.03181244, -0.11998737, -0.07825229]])

In [49]:
mat_aa = np.mat(np.random.randint(10,size=4).reshape(4,1))
mat_bb = np.mat(np.random.randint(10,size=5).reshape(1,5))

In [50]:
mat_aa

matrix([[5],
        [8],
        [3],
        [8]])

In [51]:
mat_bb

matrix([[3, 5, 5, 4, 0]])

In [52]:
mat_aa * mat_bb

matrix([[15, 25, 25, 20,  0],
        [24, 40, 40, 32,  0],
        [ 9, 15, 15, 12,  0],
        [24, 40, 40, 32,  0]])

In [55]:
mat_a

matrix([[0, 4, 5, 3, 4],
        [6, 6, 0, 7, 0],
        [0, 9, 5, 7, 2],
        [0, 0, 5, 5, 0]])

In [56]:
np.sum(mat_a, axis=0)

matrix([[ 6, 19, 15, 22,  6]])

In [57]:
np.sum(mat_a, axis=1)

matrix([[16],
        [19],
        [23],
        [10]])

In [58]:
np.sum(mat_a)

68

# save load

In [59]:
x = np.mat(np.arange(15).reshape(3,5))
y = np.mat(np.arange(45).reshape(9,5))

In [65]:
np.save('x', x)

In [66]:
t = np.load('x.npy')
t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
np.savez('xy',x=x,y=y)

In [71]:
tt = np.load('xy.npz')

In [72]:
tt

In [73]:
tt['x']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [74]:
tt['y']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])